export { default as Text } from "./text"
export { default as Screen, InScreen, OutScreen } from "./screen"
export { default as Carousel } from "./carousel"
export { default as Space } from "./space"
export { default as Button } from "./button"
export { default as ButtonSwitch } from "./buttonSwitch"
export { default as RoundShadow } from "./roundShadow"
export { default as MovieInfo } from "./movieInfo"
export { default as Modal } from "./modal"
export { default as LikeSlideContainer } from "./likeSlideContainer"
export { default as NavigationHeader } from "./navigation/navigationHeader"
export { default as DrawerView } from "./customDrawer/DrawerView"
export { default as Header } from "./header"
export { default as SearchInput } from "./searchInput"
export { default as Book } from "./book"
export { default as TextInput } from "./textInput"
export { default as YoutubePlayer } from "react-native-youtube-iframe"

export { AntDesign, Feather } from "@expo/vector-icons"
